### ISSUE TITLE
Help -> Learn More goes to a URL (https://boosthub.io/) that doesn't appear functional

### ISSUE THREAD

**Issue by dmaltsiniotis** [BoostIO/BoostNote.next-local#12] opened 2021-07-23 04:15 UTC
# Current behavior
When navigating the menu items and selecting `Help -> Learn More`, a browser window opens to https://boosthub.io/. This URI appears to be nonfunctional at this time. I'm not sure if this is a transitory issue, or if the URI needs to be updated.

**Selecting this:**
![boost2](https://user-images.githubusercontent.com/106233/126736680-282f0f77-61b7-4b6e-ac80-19bf520e9616.jpg)

**Results in:**
![boost](https://user-images.githubusercontent.com/106233/126736555-6aa6572b-0af6-462e-9012-642796daf53e.jpg)

# Expected behavior
A URI is launched to an area where I can, in fact, learn more. Perhaps updated to https://boostnote.io/ ?

# Steps to reproduce
Select Help -> Learn more from the current version of Boost Note.

# Environment

## Desktop
- Boost Note.next version: 0.20.2
- OS version and name: Windows 10 Pro

**Comment by Rokt33r** [comment] 2021-08-19 09:58
Transferred to BoostNote.next-local since the issue is already resolved from BoostNote.next repotisory

**Closed** 2021-08-19 16:12 UTC
